name: certracker
description: "CerTracker is your all-in-one platform designed to simplify and streamline the management of your healthcare certifications and credentials. Our platform is packed with features that enable healthcare workers to easily manage, monitor, and safeguard essential records, providing a seamless way to stay compliant and maintain peace of mind."
version: 1.0.0+7

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  pdf: ^3.10.7
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.1  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/login/
    - assets/images/signup/
    - assets/images/forgetpassword/
    - assets/images/icons/
