// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQDmrezS6tE5Pn9ocC_R5CZ7PtJSog4EA',
    appId: '1:912576608221:web:a4e4a888a1526157f9a834',
    messagingSenderId: '912576608221',
    projectId: 'certracker',
    authDomain: 'certracker.firebaseapp.com',
    databaseURL: 'https://certracker-default-rtdb.firebaseio.com',
    storageBucket: 'certracker.appspot.com',
    measurementId: 'G-0HCDHT9EVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRjnrk0iYXLrziZToCKUg82-hnw8cxZw',
    appId: '1:912576608221:android:d312d65a8aef0289f9a834',
    messagingSenderId: '912576608221',
    projectId: 'certracker',
    databaseURL: 'https://certracker-default-rtdb.firebaseio.com',
    storageBucket: 'certracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBM7xusxdC9OFw6GUUopky2TMHOjV280Y',
    appId: '1:912576608221:ios:3ee7c39264ec8412f9a834',
    messagingSenderId: '912576608221',
    projectId: 'certracker',
    databaseURL: 'https://certracker-default-rtdb.firebaseio.com',
    storageBucket: 'certracker.appspot.com',
    androidClientId: '912576608221-dsfnnvmi88ooq9e7n0khhg6s1cekre2b.apps.googleusercontent.com',
    iosClientId: '912576608221-5ndbho3g3inbte2m7jjjugaijlhjfbvj.apps.googleusercontent.com',
    iosBundleId: 'com.rn.certracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBM7xusxdC9OFw6GUUopky2TMHOjV280Y',
    appId: '1:912576608221:ios:42bf0087d4a83b6ff9a834',
    messagingSenderId: '912576608221',
    projectId: 'certracker',
    databaseURL: 'https://certracker-default-rtdb.firebaseio.com',
    storageBucket: 'certracker.appspot.com',
    androidClientId: '912576608221-dsfnnvmi88ooq9e7n0khhg6s1cekre2b.apps.googleusercontent.com',
    iosClientId: '912576608221-re3qn0rthi5fnt2hn6ojch3fhq5nt88a.apps.googleusercontent.com',
    iosBundleId: 'com.rn.certracker.RunnerTests',
  );
}
